---

- name: Configuración del servidor (instalando docker, configurando ssh)
  gather_facts: No
  hosts: all

  tasks:
    - name: Apagando el firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Instalando yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Descargando el repo de Docker
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Instalando Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Iniciar & Activar Docker
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Descargando Docker-Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'
        force: yes
      become: yes

    - name: Dando permisos a docker-compose
      shell: chmod +x /usr/local/bin/docker-compose

    - name: Creando acceso directo de docker-compose
      ansible.builtin.file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        owner: root
        group: wheel
        state: link
    
    - name: Copiando archivos de configuracion de ssh
      copy:
        src: ./sshd_config
        dest: /etc/ssh/sshd_config

    - name: Reiniciando servicio de ssh para aplicar los cambios
      shell: sleep 3; systemctl restart sshd
      async: 1
      poll: 0