---

- name: Configuración del servidor de backups
  gather_facts: no
  hosts: backup
  vars:
    backup_user: backup
    backup_pass: mnoseadmin1234
    newuser: ''
  become: yes

  tasks:
    - name: Apagando el firewall
      systemd:
        name: firewalld
        state: stopped
        enabled: nombre

   #- import_tasks: ./tasks/ssh_config.yml

    - name: Creando usuario backup
      user:
        name: "{{backup_user}}"
        group: "wheel"
        password: "{{backup_pass}}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
      register: newuser

    - name: Nuevo usuario
      debug:
        var: newuser

    - name: Copiando clave publica hacia el servidor de base de datos
      authorized_key:
        user: backup
        state: present
        key: "{{ newuser.ssh_public_key }}"
      delegate_to: database_master

    - name: Copiando script para hacer backups
      copy:
        src: ../config_files/script_backup.sh
        dest: "/home/{{backup_user}}/script_backup.sh"

    - name: Copiando archivo crontab
      copy:
        src: ../config_files/crontab
        dest: /etc/crontab