---

- name: Configuración del servidor de backups
  gather_facts: no
  hosts: backup_server

  tasks:
    - name: Apagando el firewall
      systemd:
        name: firewalld
        state: stopped
        enabled: no
      become: yes

    - import_tasks: ./tasks/ssh_config.yml

    - name: Creando usuario backup
      user:
        name: "backup"
        group: "wheel"
        password: "backup"
      become: yes

    - name: Copiando script para hacer backups
      copy:
        src: ./script_backup.sh
        dest: /home/backup/script_backup.sh
      become: yes

    - name: Copiando archivo crontab
      copy:
        src: ./crontab
        dest: /etc/crontab
      become: yes