---

- name: Configuración del servidor de base de datos
  gather_facts: no
  hosts: database_master
  vars:
    root_db_password: mnoseadmin1234

  tasks:
    - name: Apagando el firewall
      systemd:
        name: firewalld
        state: stopped
        enabled: no
      become: yes

    - name: Copiando dump
      copy:
        src: ../config_files/database.sql
        dest: /tmp/database.sql
      become: yes

    - name: importando el database
      mysql_db:
        name: database
        state: import
        target: /tmp/database.sql
        login_host: 127.0.0.1
        login_user: root
        login_password: "{{root_db_password}}"
        #delegate_to: neo_development 