---

- name: Desplegar proyecto a produccion
  connection: ssh
  hosts: main_server
  gather_facts: No
  vars:
    ansible_ssh_private_key_file: "/home/lucas/.ssh/server_proyecto.pem"
  vars_prompt:
    - name: "githubtoken"
      prompt: "Ingresa tu github token"
      private: yes
  
  tasks:
    - name: Instalando git
      yum:
        name:
          - git
      become: yes

    - name: Clonando repositorio del backend
      git:
        repo: https://{{ githubtoken }}:x-oauth-basic@github.com/Fenware/backend.git
        dest: "/var/backend"
        update: yes
      become: yes
    
    - name: Creando carpeta frontend
      file:
        path: "/var/frontend"
        state: directory
      become: yes

    - name: Copiando docker-compose.yml para levantar los frontends y el microservicio
      copy:
        src: "../config_files/docker-compose.yml"
        dest: "/var/frontend"
      become: yes
  
    - name: Start docker service
      service: name=docker state=started
      
    - name: Docker Compose - start backend
      shell: cd /var/backend/ && docker-compose -f docker-compose.prod.yml build && docker-compose -f docker-compose.prod.yml up -d
      become: yes
      
    - name: Docker Compose - start frontend and ws-microservice
      shell: cd /var/frontend/ && docker-compose up -d
      become: yes

